version: '3.8'

services:
  nestjs_app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'hot_combien_app'
      MYSQL_USER: 'hot_combien_user'
      MYSQL_PASSWORD: 'passworduser'
      MYSQL_ROOT_PASSWORD: 'passwrdroot'
    ports:
      - "3306:3306"

  apache_server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - nestjs_app
      - mysql_db
