services:
  nestjs_app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mysql_db

  react_app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    stdin_open: true
    tty: true
    depends_on:
      - nestjs_app

  mysql_db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'hot_combien_app'
      MYSQL_USER: 'hot_combien_user'
      MYSQL_PASSWORD: 'passworduser'
      MYSQL_ROOT_PASSWORD: 'passwrdroot'
      MYSQL_TCP_PORT: '3306'
    ports:
      - "3306:3306"

  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
